services:
  postgres:
    image: postgres:13
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=database_development
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=asmz5488@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin